import sys
with open('write_vit.py', 'w') as f:
    f.write('import sys\n')
    f.write('code = """import sys\n')
    f.write('import json\n')
    f.write('import torch\n')
    f.write('import timm\n')
    f.write('from PIL import Image\n')
    f.write('from timm.data import resolve_data_config\n')
    f.write('from timm.data.transforms_factory import create_transform\n\n')
    f.write('class ViTProcessor:\n')
    f.write('    def __init__(self):\n')
    f.write('        print("[AI] Loading ViT model...")\n')
    f.write('        self.model = timm.create_model("vit_base_patch16_224", pretrained=True, num_classes=0)\n')
    f.write('        self.model.eval()\n')
    f.write('        config = resolve_data_config({}, model=self.model)\n')
    f.write('        self.transform = create_transform(**config)\n')
    f.write('        print("[SUCCESS] ViT model loaded")\n\n')
    f.write('    def extract_embedding(self, image_path):\n')
    f.write('        image = Image.open(image_path).convert("RGB")\n')
    f.write('        input_tensor = self.transform(image).unsqueeze(0)\n')
    f.write('        with torch.no_grad():\n')
    f.write('            embedding = self.model(input_tensor).squeeze().numpy()\n')
    f.write('        return embedding\n\n')
    f.write('if __name__ == "__main__":\n')
    f.write('    if len(sys.argv) < 2:\n')
    f.write('        print(json.dumps({"success": False}))\n')
    f.write('        sys.exit(1)\n\n')
    f.write('    try:\n')
    f.write('        processor = ViTProcessor()\n')
    f.write('        emb = processor.extract_embedding(sys.argv[1])\n')
    f.write('        print(f"[SUCCESS] Extracted {len(emb)} features")\n')
    f.write('        output = {"success": True, "embeddings": emb.tolist(), "dimensions": len(emb), "model": "ViT-Base-224"}\n')
    f.write('        print(json.dumps(output))\n')
    f.write('    except Exception as e:\n')
    f.write('        print(json.dumps({"success": False, "error": str(e)}))\n')
    f.write('        sys.exit(1)\n')
    f.write('"""\n')
    f.write('with open("ai_processor_enhanced.py", "w") as out:\n')
    f.write('    out.write(code)\n')
    f.write('print("ViT processor created")\n')
